spring.application.name=projeto_sala_de_aula
spring.datasource.url=jdbc:mysql://localhost:3306/projeto_aula?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Developer@3306
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.sjow-sql=true